TOOLS: bin/generate-all.sh should skip .vscode (#3901)
# Issue

bin/generate-all.sh is trying to reformat VSCode's launch.json, but it
can't because it is not strict json.

```
Reformatting: ./.vscode/launch.json
ERROR: Expecting value: line 17 column 17 (char 465)
```

# Resolution

bin/generate-all.sh should skip the .vscode directory.