BUNNY_DNS: Add support for PullZone (PZ) record type (#4053)
<!--
## Before submiting a pull request

Please make sure you've run the following commands from the root
directory.

    bin/generate-all.sh

(this runs commands like "go generate", fixes formatting, and so on)

## Release changelog section

Help keep the release changelog clear by pre-naming the proper section
in the GitHub pull request title.

Some examples:
* CICD: Add required GHA permissions for goreleaser
* DOCS: Fixed providers with "contributor support" table
* ROUTE53: Allow R53_ALIAS records to enable target health evaluation

More examples/context can be found in the file .goreleaser.yml under the
'build' > 'changelog' key.
!-->

This PR adds support for the Bunny DNS custom record type `PullZone` (or
`PZ`), which maps a domain name to a Bunny CDN pull zone.

It looks like this in the config:

```js
D("example.com", REG_NONE, DnsProvider(DSP_BUNNY_DNS),
    BUNNY_DNS_PZ("@", 12345),
);
```

Where `12345` is the ID of the CDN pull zone, which can be retrieved
from the Bunny dashboard URL (e.g.
`https://dash.bunny.net/cdn/5269987/general/hostnames`).

It looks like this in the UI:

<img width="1483" height="207" alt="image"
src="https://github.com/user-attachments/assets/d24e640f-8694-48a5-864f-2f75df6a69cb"
/>

Two things for reviewers:

- The Bunny DNS API for PZ records is very messy: when you create a PZ
record you specify `PullZoneID` as an int64, but when you retrieve the
zone records the ID is returned as a string in a field named `LinkName`.
This isn't clearly documented so I'll confirm with Bunny support if this
is the right way to do it and will report back with a comment in this
PR.
- Given the above inconsistency, I've added a unit test for the
conversion and an integration test for the custom record. The
integration test however requires the IDs of 2 pull zones to work
(create+change). I suppose these IDs should be made configurable through
`profiles.json`, but at a first glance I don't see other tests requiring
options so for now I've left the 2 IDs hardcoded (which work only on my
test account).

I may have also missed something else since this is my first
contribution to this project.

Thanks!

P.S. the following integration test is failing with Bunny DNS but I
believe this is unrelated to this PR:

```
        --- FAIL: TestDNSProviders/dmw-testdnscontrol.com/25:NS_only_APEX:Single_NS_at_apex (0.17s)
```

---------

Co-authored-by: Tom Limoncelli <6293917+tlimoncelli@users.noreply.github.com>