Fix apex CNAME validation
Cloudflare supports apex CNAMEs, but the validation was throwing
errors like this because there were also MX records there:

ERROR: Cannot have CNAME and MX record with same name: example.com

Better validation would only allow apex CNAMEs on providers that
actually support it, but since that wasn't checked before, I
figure this is a good interim solution.